jobs <- c(
  composer       = "3",
  cinematography = "6",
  sound          = "9",
  costumes       = "12",
  actor          = "1",
  screenwriter   = "4",
  production     = "7",
  scenography    = "10",
  creator        = "13",
  director       = "2",
  author         = "5",
  edit           = "8",
  mask           = "11",
  performers     = "14",
  "skladatel"    = "3",
  "kameraman"    = "6",
  "zvukař"       = "9",
  "kostymér"     = "12",
  "herec"        = "1",
  "scenárista"   = "4",
  "producent"    = "7",
  "scénograf"    = "10",
  "tvůrce"       = "13",
  "režisér"      = "2",
  "spisovatel"   = "5",
  "střihač"      = "8",
  "maskér"       = "11",
  "účinkující"   = "14"
)

names(jobs) <- tolower(names(jobs))

type <- c(
  film                = "0",
  tv_show             = "3",
  tv_film             = "2",
  program             = "4",
  student_film        = "7",
  amateur_film        = "8",
  theater_play        = "5",
  music_video         = "9",
  concert             = "6",
  "seriál"            = "3",
  "TV film"           = "2",
  "pořad"             = "4",
  "studentský film"   = "7",
  "amatérský film"    = "8",
  "divadelní záznam"  = "5",
  "hudební videoklip" = "9",
  "koncert"           = "6"
)

names(type) <- tolower(names(type))

origin <- c(
  "Afghánistán" = "3",
  "Albánie" = "4",
  "Alžírsko" = "5",
  "Andorra" = "6",
  "Angola" = "7",
  "Antigua a Barbuda" = "8",
  "Argentina" = "9",
  "Arménie" = "10",
  "Aruba" = "205",
  "Austrálie" = "11",
  "Ázerbájdžán" = "185",
  "Bahamy" = "12",
  "Bahrajn" = "13",
  "Bangladéš" = "14",
  "Barbados" = "15",
  "Belgie" = "16",
  "Belize" = "17",
  "Bělorusko" = "28",
  "Benin" = "18",
  "Bhútán" = "19",
  "Bolívie" = "20",
  "Bosna a Hercegovina" = "21",
  "Botswana" = "22",
  "Brazílie" = "23",
  "Brunej" = "24",
  "Bulharsko" = "25",
  "Burkina Faso" = "26",
  "Burundi" = "27",
  "Curacao" = "229",
  "Čad" = "187",
  "Černá Hora" = "190",
  "Česko" = "1",
  "Československo" = "197",
  "Čína" = "195",
  "Dánsko" = "34",
  "Demokratická republika Kongo" = "31",
  "Dominika" = "32",
  "Dominikánská republika" = "33",
  "Džibutsko" = "35",
  "Egypt" = "36",
  "Ekvádor" = "37",
  "Eritrea" = "38",
  "Estonsko" = "39",
  "Etiopie" = "40",
  "Faerské ostrovy" = "211",
  "Federativní státy Mikronésie" = "108",
  "Fed. rep. Jugoslávie" = "200",
  "Fidži" = "41",
  "Filipíny" = "42",
  "Finsko" = "43",
  "Francie" = "44",
  "Francouzská Polynésie" = "213",
  "Gabon" = "45",
  "Gambie" = "46",
  "Ghana" = "47",
  "Grenada" = "48",
  "Grónsko" = "206",
  "Gruzie" = "49",
  "Guadeloupe" = "214",
  "Guatemala" = "50",
  "Guinea" = "51",
  "Guinea-Bissau" = "52",
  "Guyana" = "53",
  "Haiti" = "54",
  "Honduras" = "55",
  "Hongkong" = "196",
  "Chile" = "29",
  "Chorvatsko" = "30",
  "Indie" = "56",
  "Indonésie" = "57",
  "Irák" = "59",
  "Írán" = "186",
  "Irsko" = "58",
  "Island" = "60",
  "Itálie" = "61",
  "Izrael" = "62",
  "Jamajka" = "63",
  "Japonsko" = "64",
  "Jemen" = "65",
  "Jihoafrická republika" = "66",
  "Jižní Korea" = "67",
  "Jordánsko" = "68",
  "Jugoslávie" = "201",
  "Kambodža" = "69",
  "Kamerun" = "70",
  "Kanada" = "71",
  "Kapverdy" = "72",
  "Katar" = "73",
  "Kazachstán" = "74",
  "Keňa" = "75",
  "Kiribati" = "76",
  "Kolumbie" = "77",
  "Komory" = "78",
  "Kongo" = "79",
  "Korea" = "208",
  "Kosovo" = "80",
  "Kostarika" = "81",
  "Království Srbů, Chorvatů a Slovinců" = "231",
  "Kréta" = "210",
  "Kuba" = "82",
  "Kuvajt" = "83",
  "Kypr" = "84",
  "Kyrgyzstán" = "85",
  "Laos" = "86",
  "Lesotho" = "87",
  "Libanon" = "88",
  "Libérie" = "90",
  "Libye" = "89",
  "Lichtenštejnsko" = "91",
  "Litva" = "92",
  "Lotyšsko" = "93",
  "Lucembursko" = "94",
  "Macao" = "221",
  "Madagaskar" = "95",
  "Maďarské království" = "230",
  "Maďarsko" = "106",
  "Makedonie" = "96",
  "Malajsie" = "97",
  "Malawi" = "98",
  "Maledivy" = "99",
  "Mali" = "100",
  "Malta" = "101",
  "Maroko" = "102",
  "Marshallovy ostrovy" = "103",
  "Martinik" = "215",
  "Mauricius" = "104",
  "Mauritánie" = "105",
  "Mayotte" = "216",
  "Mexiko" = "107",
  "Moldavsko" = "109",
  "Monako" = "110",
  "Mongolsko" = "111",
  "Mosambik" = "112",
  "Myanmar" = "113",
  "Namibie" = "114",
  "Nauru" = "115",
  "Německá říše" = "226",
  "Německo" = "123",
  "Nepál" = "116",
  "Niger" = "117",
  "Nigérie" = "118",
  "Nikaragua" = "119",
  "Nizozemsko" = "120",
  "Norsko" = "121",
  "Nová Kaledonie" = "217",
  "Nový Zéland" = "122",
  "Omán" = "124",
  "Osmanská říše" = "228",
  "Pákistán" = "133",
  "Palau" = "125",
  "Palestina" = "202",
  "Panama" = "126",
  "Papua-Nová Guinea" = "127",
  "Paraguay" = "128",
  "Peru" = "129",
  "Pobřeží slonoviny" = "130",
  "Polsko" = "131",
  "Portoriko" = "203",
  "Portugalsko" = "132",
  "Protektorát Čechy a Morava" = "224",
  "Rakouské císařství" = "222",
  "Rakousko" = "134",
  "Rakousko-Uhersko" = "204",
  "Rovníková Guinea" = "135",
  "Rumunsko" = "136",
  "Ruské impérium" = "220",
  "Rusko" = "137",
  "Rwanda" = "138",
  "Řecko" = "189",
  "Saint-Pierre a Miquelon" = "218",
  "Salvador" = "139",
  "Samoa" = "140",
  "San Marino" = "141",
  "Saúdská Arábie" = "142",
  "Senegal" = "143",
  "Severní Korea" = "144",
  "Severní Makedonie" = "233",
  "Seychely" = "145",
  "Sierra Leone" = "146",
  "Singapur" = "147",
  "Slovensko" = "2",
  "Slovenský stát" = "225",
  "Slovinsko" = "148",
  "Somálsko" = "149",
  "Sovětský svaz" = "199",
  "Spojené arabské emiráty" = "150",
  "Srbsko" = "151",
  "Srbsko a Černá Hora" = "209",
  "Středoafrická republika" = "152",
  "Súdán" = "159",
  "Surinam" = "153",
  "Svatá Lucie" = "154",
  "Svatý Kryštof a Nevis" = "155",
  "Svatý Tomáš a Princův ostrov" = "156",
  "Svatý Vincenc a Grenadiny" = "157",
  "Svazijsko" = "158",
  "Sýrie" = "160",
  "Šalamounovy ostrovy" = "188",
  "Španělsko" = "191",
  "Šrí Lanka" = "192",
  "Švédsko" = "193",
  "Švédsko-norská unie" = "223",
  "Švýcarsko" = "194",
  "Tádžikistán" = "171",
  "Tanzanie" = "161",
  "Thajsko" = "163",
  "Tchaj-wan" = "162",
  "Tibet" = "212",
  "Togo" = "164",
  "Tonga" = "165",
  "Trinidad a Tobago" = "166",
  "Tunisko" = "167",
  "Turecko" = "168",
  "Turkmenistán" = "169",
  "Tuvalu" = "170",
  "Uganda" = "173",
  "Uherské království" = "227",
  "Ukrajina" = "174",
  "Uruguay" = "175",
  "USA" = "172",
  "Uzbekistán" = "176",
  "Vanuatu" = "177",
  "Vatikán" = "178",
  "Velká Británie" = "179",
  "Venezuela" = "180",
  "Vietnam" = "181",
  "Východní Německo" = "198",
  "Východní Timor" = "182",
  "Wallis a Futuna" = "219",
  "Zambie" = "183",
  "Západní Německo" = "207",
  "Zimbabwe" = "184"
)

names(origin) <- tolower(names(origin))

gender <- c(male = "1", female = "2", "1" = "1", "2" = "2")

fields <- c(
  "Tagy"            = "tag",
  "Herci"           = "actor",
  "Režiséři"        = "director",
  "Skladatelé"      = "composer",
  "Scenáristé"      = "screenwriter",
  "Autoři předlohy" = "author",
  "Producenti"      = "production",
  "Kameramani"      = "cinematographer",
  "Střihači"        = "edit",
  "Zvukaři"         = "sound",
  "Scénografové"    = "scenography",
  "Maskéři"         = "mask",
  "Kostyméři"       = "costumes",
  tag               = "tag",
  actor             = "actor",
  director          = "director",
  composer          = "composer",
  screenwriter      = "screenwriter",
  author            = "author",
  production        = "production",
  cinematographer   = "cinematographer",
  edit              = "edit",
  sound             = "sound",
  scenography       = "scenography",
  mask              = "mask",
  costumes          = "costumes"
)

names(fields) <- tolower(names(fields))

genre <- c(
  "Akční"          = "1",
  "Animovaný"      = "3",
  "Dobrodružný"    = "11",
  "Dokumentární"   = "13",
  "Drama"          = "2",
  "Erotický"       = "45",
  "Experimentální" = "26",
  "Fantasy"        = "4",
  "Film-Noir"      = "20",
  "Historický"     = "21",
  "Horor"          = "5",
  "Hudební"        = "22",
  "IMAX"           = "28",
  "Katastrofický"  = "39",
  "Komedie"        = "9",
  "Krimi"          = "18",
  "Krátkometrážní" = "14",
  "Loutkový"       = "23",
  "Muzikál"        = "12",
  "Mysteriózní"    = "16",
  "Naučný"         = "44",
  "Podobenství"    = "25",
  "Poetický"       = "27",
  "Pohádka"        = "30",
  "Pornografický"  = "10",
  "Povídkový"      = "29",
  "Psychologický"  = "31",
  "Publicistický"  = "33",
  "Reality-TV"     = "35",
  "Road movie"     = "40",
  "Rodinný"        = "6",
  "Romantický"     = "15",
  "Sci-Fi"         = "7",
  "Soutěžní"       = "36",
  "Sportovní"      = "32",
  "Stand-up"       = "43",
  "Talk-show"      = "34",
  "Taneční"        = "41",
  "Telenovela"     = "38",
  "Thriller"       = "8",
  "Válečný"        = "17",
  "Western"        = "19",
  "Zábavný"        = "42",
  "Životopisný"    = "37"
)

names(genre) <- tolower(names(genre))

mode <- c(exact = "1", all = "2", any = "3")

.opts <- list(

  # /film - includes films, TV shows, TV show episodes.
  title = list(

    type = c(type, compilation = "14", "video kompilace" = "14"),

    mode = mode, genre = genre, origin = origin, fields = fields,

    additional = c(
      with_trivia           = "with_trivia",
      with_awards           = "with_awards",
      with_photos           = "with_photos",
      in_cinemas            = "in_cinemas",
      on_tv                 = "on_tv",
      on_vod                = "on_vod",
      with_collection       = "with_collection",
      with_bazaar           = "with_bazaar",
      on_bluray             = "on_bluray",
      on_dvd                = "on_dvd",
      with_comments         = "with_comments",
      with_videos           = "with_videos",
      "se zajímavostmi"     = "with_trivia",
      "s oceněními"         = "with_awards",
      "s galerií"           = "with_photos",
      "běží v kinech"       = "in_cinemas",
      "poběží v TV"         = "on_tv",
      "k přehrání na VOD"   = "on_vod",
      "ve filmotéce"        = "with_collection",
      "ve filmotéce prodej/sháňka" = "with_bazaar",
      "ke koupi na Blu-ray" = "on_bluray",
      "ke koupi na DVD"     = "on_dvd",
      "s recenzemi"         = "with_comments",
      "s videi"             = "with_videos"
    )
  ),

  # /creator
  creator = list(

    type = jobs, origin = origin, gender = gender,

    additional = list(
      with_trivia       = "with_trivia",
      with_awards       = "with_awards",
      with_photos       = "with_photos",
      with_biography    = "with_biography",
      with_contact      = "with_contact",
      with_forum_posts  = "with_forum_posts",
      "se zajímavostmi" = "with_trivia",
      "s oceněními"     = "with_awards",
      "s galerií"       = "with_photos",
      "s biografií"     = "with_biography",
      "s kontakty"      = "with_contact",
      "s diskuzí"       = "with_forum_posts"
    )
  ),

  # /?
  rank = list(

    genre = genre,

    type = c(type, tv_show_season = "10", "seriál - série" = "10"),

    origin = c(
      origin,
      evropa  = "continent-1",
      amerika = "continent-2",
      asie    = "continent-3",
      afrika  = "continent-4",
      "austrálie a oceánie" = "continent-5"
    ),

    fields = c(
      actor      = "actor",
      director   = "director",
      Herci      = "actor",
      "Režiséři" = "director"
    )
  )
)

usethis::use_data(.opts, internal = TRUE, overwrite = TRUE)
